# Generated by Django 6.0.4 on 2026-04-24 15:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('khasra_number', models.CharField(db_index=True, max_length=100)),
                ('square_footage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('land_use', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('agricultural', 'Agricultural')], max_length=25)),
                ('status', models.CharField(choices=[('available', 'Available'), ('locked', 'Locked'), ('pending', 'Pending')], default='available', max_length=20)),
                ('mauza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='topology.mauza')),
            ],
            options={
                'unique_together': {('mauza', 'khasra_number')},
            },
        ),
    ]
