# Generated by Django 6.0.4 on 2026-04-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesession',
            name='session_key',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
