# Generated by Django 6.0.4 on 2026-04-24 04:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel_uuid', models.UUIDField(db_index=True, unique=True)),
                ('prov_code', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
