# Generated by Django 6.0.4 on 2026-04-26 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel_id', models.UUIDField(help_text='the UUID of the lanparcel from reg serv')),
                ('buyer_uuid', models.UUIDField(help_text='the UUID of the buyer from iden serv')),
                ('seller_uuid', models.UUIDField(help_text='the UUID of the seller from iden serv')),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('funded', 'Funded'), ('verified', 'Verified'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
