# Generated by Django 6.0.4 on 2026-04-25 04:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_owner_uuid', models.UUIDField(blank=True, null=True)),
                ('to_owner_uuid', models.UUIDField()),
                ('transaction_ref', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='parcels.landparcel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_uuid', models.UUIDField(db_index=True)),
                ('share_perc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titles', to='parcels.landparcel')),
            ],
            options={
                'unique_together': {('parcel', 'owner_uuid')},
            },
        ),
    ]
