# Generated by Django 6.0.4 on 2026-04-25 15:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=200)),
                ('loan_acc_num', models.CharField(max_length=100)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('pkr', 'PKR'), ('usd', 'USD'), ('gbp', 'GBP'), ('eur', 'EUR')], default='pkr', max_length=15)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='parcels.landparcel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StayOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('court_name', models.CharField(max_length=200)),
                ('case_num', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stay_orders', to='parcels.landparcel')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
